### ISSUE TITLE
How to train for a new dataset ?

### ISSUE THREAD

**Issue by MohamedAliRashad** [VITA-Group/FasterSeg#36]
So i have been playing a little bit with the `config_search.py` to adapt my new dataset to the pipeline but i kept getting this error 
```
RuntimeError: merge_sort: failed on 2nd step: device-side assert triggered
```
After some research i knew it's a problem with the configuration i did to the dataset but the problem is that i don't know what every parameter do, so can anyone elaborate on this ?

**Comment by chenwydj** [comment]
Hi @MohamedAliRashad!

Thank you for your interest in our work!

Actually I have no idea what the problem is... The only place I found may be related to the `merge_sort` is the [OHEM loss](https://github.com/TAMU-VITA/FasterSeg/blob/master/search/loss.py#L75), but I'm not sure if this the where the error is raised.

**Comment by MohamedAliRashad** [comment]
@chenwydj Can you provide a description for every parameter in `config.py` ?

**Comment by chenwydj** [comment]
Hi @MohamedAliRashad! I have updated the comments for the configure files.
